export const items: {[key: string]: {image:string, name:string, description:string, price:string, rating:number}} = {
    item1: {
        image: '/images/Autumnking.png',
        name: 'Carrot Seeds (Autumn King)',
        description: 'Autumn King is a variety of carrot that can be stored for a long time after harvesting. It produces an abundant crop of large orange/reddish carrots that are sweet tasting.',
        price: '3.25',
        rating: 4.5,
    },
    item2: {
        image: '/images/BasilGenoveseSquare.png',
        name: 'Basil Seeds',
        description: 'Basil genovese is an annual herb with medium-sized leaves. It has a strong smell and good flavor. Basil is great for making pesto with or adding to any Italian meal. Genovese Basil seeds can be planted year-round in a pot on your window sill. Genovese Basil is also commonly called Sweet Basil.',
        price: '2.75',
        rating: 4,
    },
    item3: {
        image: '/images/BroccoliGreenCalabrese-Square.png',
        name: 'Broccoli Seeds',
        description: 'Green Calabrese Broccoli is a close relation of Cauliflower. The head, side shoots and the sprouts of this plant can all be eaten.',
        price: '3.50',
        rating: 4,
    },
    item4: {
        image: '/images/CabbageSavoy-BloemendaalseGeleSquare.png',
        name: 'Cabbage Seeds',
        description: 'The variety of this Savoy Cabbage is "Bloemendaalse Gele". It is the hardiest breed of all savoy cabbage varieties. It is a slightly curled cabbage and has a very good and tender taste. Savoy cabbage can withstand some frost, meaning it can stay outside for quite some time, and be harvested over Autumn/Winter.',
        price: '3.95',
        rating: 5,
    },
    item5: {
        image: '/images/CalendulaOfficinalis_PotMarigoldSquare.png',
        name: 'Calendula Seeds',
        description: 'Calendula has singular, orange flowers with a dark heart. It is very easy to grow. It is used for medicinal, cosmetic and culinary purposes. Pot Marigold flowers are edible, and can be used to garnish dishes, and for seasoning.',
        price: '2.50',
        rating: 4,
    },
    item6: {
        image: '/images/CarrotNantes2Square2.png',
        name: 'Carrot Seeds',
        description: 'Carrots produce really nice cylindrical carrots. If you thin down the seedlings, and leave a wider than recommended spacing, the carrots will grow larger. This variety of carrot produces nice cylindrical carrots with a sweet taste. Planting can take place as late as August for this variety.',
        price: '2.95',
        rating: 5,
    },
    item7: {
        image: '/images/ChilliPepperWestlandeLangeRodeSquare.png',
        name: 'Chilli Pepper Seeds',
        description: 'Chilli Pepper Westlandse Lange Rode will produce small hot chilli peppers. The chilli peppers can also be dried and stored as well as being used fresh.',
        price: '4.50',
        rating: 4,
    },
    item8: {
        image: '/images/ChivesinFlowerSquare.png',
        name: 'Chives Seeds',
        description: 'Chives are an easy to grow perennial herb. They produce edible leaves that have a mild onion flavor. If allowed to flower, Chives also produce beautiful pink flowers that are also edible. Their flowers are very beneficial to pollinators. The leaves make a great garnish, or a nice last-minute addition of flavor to any dish.',
        price: '1.95',
        rating: 4,
    },
    item9: {
        image: '/images/Cobrasquare.png',
        name: 'Cobra Organic Seeds',
        description: 'Cobra is a great variety of French Bean, as it produces a heavy yield over a long period. It is a mid-early variety, that suitable to be grown both in a greenhouse, as well as outdoors. Cobra produces light green stringless pole beans.',
        price: '5.25',
        rating: 5,
    },
    item10: {
        image: '/images/CorianderSquare.png',
        name: 'Coriander Seeds',
        description: 'Coriander is an annual herb. It has a strong smell and flavor. It is grown for both its leaves, and the seed it produces. Coriander seeds can be harvested when they turn brown, this is usually in September. Coriander is also known as Cilantro.',
        price: '1.75',
        rating: 5,
    },
    item11: {
        image: '/images/CosmosSquare1.png',
        name: 'Cosmos Seeds',
        description: 'Cosmos produces beautiful big flowers, varying in color from white to dark pink. The flowers can be used in vases as a cut flower. Cosmos will bloom continually when the flowers are cut regularly. Cosmos can grow to a height of 110cm.',
        price: '3.50',
        rating: 4,
    },
    item12: {
        image: '/images/Cucumbertelegraphedimprovedsquare.png',
        name: 'Cucumber Seeds',
        description: 'This cucumber seed is a popular choice for home gardens and produces medium to long, dark green cucumbers. The plants can grow up to 3 meters in height when properly trained, making it a reliable option for those looking to cultivate cucumbers in their garden.',
        price: '3.25',
        rating: 5,
    },
    item13: {
        image: '/images/EchinaceaPurpleSquare3.png',
        name: 'Echinacea Seeds',
        description: 'Echinacea seeds produce a medicinal plant with large purple-red petals surrounding a central cone, making it an attractive addition to any garden. This plant is also suitable for use as a cut flower.',
        price: '4.75',
        rating: 4,
    },
    item14: {
        image: '/images/EgyptianBeetroot2.png',
        name: 'Beetroot Seeds',
        description: 'Beetroot seeds produce vibrant red roots with a sweet, earthy flavor. They are easy to grow and can be harvested for salads, roasting, or pickling. Ideal for home gardens and nutritious dishes.',
        price: '2.50',
        rating: 4,
    },
    item15: {
        image: '/images/EnglishLavenderSquare.png',
        name: 'Lavender Seeds',
        description: 'Lavender seeds yield aromatic plants with beautiful purple flowers, perfect for creating a calming garden atmosphere. Lavender is also known for its use in essential oils and as a natural insect repellent.',
        price: '3.95',
        rating: 5,
    },
    item16: {
        image: '/images/FoxgloveSquare.png',
        name: 'Foxglove Seeds',
        description: 'Foxglove seeds produce tall, striking plants with bell-shaped flowers in various shades of pink, purple, and white. They are a favorite in cottage gardens and attract pollinators like bees and butterflies.',
        price: '4.25',
        rating: 5,
    },
    item17: {
        image: '/images/KaleWestlandWinterSquare.png',
        name: 'Kale Seeds',
        description: 'Kale seeds grow into nutrient-packed leafy greens, perfect for salads, smoothies, and cooking. This hardy vegetable thrives in cool weather and provides a continuous harvest throughout the growing season.',
        price: '2.95',
        rating: 5,
    },
    item18: {
        image: '/images/LemonBalmSquare1.png',
        name: 'Lemon Balm Seeds',
        description: 'Lemon Balm seeds produce a fragrant herb with a fresh, lemony scent. This versatile herb is great for teas, culinary use, and as a natural remedy for stress relief and digestive health.',
        price: '3.75',
        rating: 4,
    },
    item19: {
        image: '/images/NerodiToscanaKaleSquare.png',
        name: 'Nerodi Toscana Seeds',
        description: 'Nerodi Toscana seeds grow into robust plants known for their deep green, savoyed leaves. This variety is popular for its flavor and is often used in Italian cooking, particularly in soups and sautés.',
        price: '3.50',
        rating: 5,
    },
    item20: {
        image: '/images/OnionIshukuraSquare.png',
        name: 'Onion Shukura Seeds',
        description: 'Onion Shukura seeds yield a variety of onion known for its mild flavor and versatility in the kitchen. These onions are ideal for both raw and cooked dishes, offering a sweet, crisp taste.',
        price: '2.95',
        rating: 4,
    },
    item21: {
        image: '/images/OnionStuttgartSquare.png',
        name: 'Onion Stuttgart Seeds',
        description: 'Onion Stuttgart seeds produce a reliable and popular onion variety with a slightly pungent flavor. These onions are excellent for storage and can be used in a wide range of culinary applications.',
        price: '3.25',
        rating: 4,
    },
    item22: {
        image: '/images/PakChoiSquare.png',
        name: 'Pak Choi Seeds',
        description: 'Pak Choi seeds grow into crisp, leafy vegetables, perfect for stir-fries, soups, and salads. This Asian green is known for its mild flavor and rapid growth, making it a staple in many kitchens.',
        price: '2.75',
        rating: 5,
    },
    item23: {
        image: '/images/PeakelvedonWonderImageSquare.png',
        name: 'Pea Kelvedon Seeds',
        description: 'Pea Kelvedon seeds produce a high-yielding variety of peas with sweet, tender pods. Ideal for fresh eating, freezing, or adding to a variety of dishes, these peas are a favorite among gardeners.',
        price: '3.50',
        rating: 5,
    },
    item24: {
        image: '/images/PumpkinSquare.png',
        name: 'Pumpkin Seeds',
        description: 'Pumpkin seeds grow into large, orange pumpkins that are perfect for carving, cooking, and decorating. These pumpkins have a rich, sweet flavor and can be used in pies, soups, and roasted dishes.',
        price: '4.95',
        rating: 4,
    },
    item25: {
        image: '/images/RocketWildPerennialSquare.png',
        name: 'Wild Rocket Seeds',
        description: 'Wild Rocket seeds produce a peppery, leafy green with a bold flavor, ideal for salads, sandwiches, and garnishes. This fast-growing plant is a favorite for adding a spicy kick to dishes.',
        price: '1.75',
        rating: 4,
    },
    item26: {
        image: '/images/Rosemary.png',
        name: 'Rosemary Seeds',
        description: 'Rosemary seeds grow into hardy, aromatic shrubs that are perfect for culinary use, especially in roasting meats and vegetables. The fragrant, needle-like leaves are also used in herbal remedies and garden landscaping.',
        price: '2.50',
        rating: 4,
    },
    item27: {
        image: '/images/SpinachEarlyGiantSquare2.png',
        name: 'Spinach Seeds',
        description: 'Spinach seeds produce a nutrient-rich, leafy green that is perfect for salads, smoothies, and cooking. Spinach is easy to grow and thrives in cool weather, offering a continuous harvest.',
        price: '2.25',
        rating: 5,
    },
    item28: {
        image: '/images/SweetPeaWildItalianSquare.png',
        name: 'Sweet Pea Seeds',
        description: 'Sweet Pea seeds yield beautiful, fragrant flowers that bloom in a variety of colors. These climbing plants are perfect for trellises and garden borders, adding both color and scent to your garden.',
        price: '3.95',
        rating: 4,
    },
    item29: {
        image: '/images/ThymeSquare1.png',
        name: 'Thyme Seeds',
        description: 'Thyme seeds produce a versatile, aromatic herb that is widely used in cooking, especially in Mediterranean dishes. Thyme is easy to grow and can be harvested for fresh use or dried for later use.',
        price: '2.50',
        rating: 5,
    },
    item30: {
        image: '/images/VerbabaSquare2.png',
        name: 'Verbena Seeds',
        description: 'Verbena seeds grow into vibrant, flowering plants that are perfect for adding color to your garden. These flowers are loved by pollinators and are excellent for hanging baskets, borders, and containers.',
        price: '4.25',
        rating: 4,
    },
    item31: {
        image: '/images/WildStrawberry.png',
        name: 'Strawberry Seeds',
        description: 'Strawberry seeds produce sweet, juicy berries that are perfect for fresh eating, desserts, and preserves. These plants are easy to grow and offer a rewarding harvest throughout the growing season.',
        price: '8.95',
        rating: 5,
    }
};
